# Definiere Variablen
ASM = nasm
CC = gcc

SRC_DIR = src
BUILD_DIR = build

.PHONY: all os_image bootloader kernel clean always

all: bootloader kernel os_image

#
# OS image
#
os_image: $(BUILD_DIR)/os.img

$(BUILD_DIR)/os.img: bootloader kernel
	fsutil file createnew $(BUILD_DIR)/os.img 1474560
	mformat -i $(BUILD_DIR)/os.img -f 1440 -v "MYOS" -B $(BUILD_DIR)/bootloader.bin ::
	mcopy -i $(BUILD_DIR)/os.img $(BUILD_DIR)/kernel.bin ::/kernel.bin

#
# Bootloader
#
bootloader: $(BUILD_DIR)/bootloader.bin

$(BUILD_DIR)/bootloader.bin: always
	$(ASM) -f bin $(SRC_DIR)/bootloader.asm -o $(BUILD_DIR)/bootloader.bin

#
# Kernel
#
kernel: $(BUILD_DIR)/kernel.bin

$(BUILD_DIR)/kernel.bin: always
	$(ASM) -f bin $(SRC_DIR)/kernel.asm -o $(BUILD_DIR)/kernel.bin

#
# Always
#
always:
	$(shell mkdir $(BUILD_DIR))

#
# Clean
#
clean:
	del /q $(BUILD_DIR)\*