# Definiere Variablen
NASM = nasm
QEMU = qemu-system-x86_64
BOOTLOADER_SRC = bootloader.asm
BOOTLOADER_BIN = output\bootloader.bin
KERNEL_SRC = kernel.asm
KERNEL_BIN = output\kernel.bin
OUTPUT_IMG = output\disk.img
TEMP_IMG = output\temp.img

# Standardziel
all: $(BOOTLOADER_BIN) $(KERNEL_BIN) $(OUTPUT_IMG)

# Erstelle das output-Verzeichnis
$(shell mkdir output)

# Erstelle den Bootloader
$(BOOTLOADER_BIN): $(BOOTLOADER_SRC)
	$(NASM) -f bin $(BOOTLOADER_SRC) -o $(BOOTLOADER_BIN)

# Erstelle den Kernel (Optional, falls du einen Kernel hinzufügen möchtest)
$(KERNEL_BIN): $(KERNEL_SRC)
	$(NASM) -f bin $(KERNEL_SRC) -o $(KERNEL_BIN)

# Erstelle die Festplatten-Image-Datei
$(OUTPUT_IMG): $(BOOTLOADER_BIN) $(KERNEL_BIN)
	fsutil file createnew output/disk.img 1474560
	mformat -i output/disk.img -f 1440 -v "MYOS" -B $(BOOTLOADER_BIN) ::
	mcopy -i output/disk.img output/kernel.bin ::/kernel.bin
	mcopy -i output/disk.img text.txt ::/text.txt

# Starte das OS in QEMU
run: $(OUTPUT_IMG)
	$(QEMU) -drive format=raw,file=$(OUTPUT_IMG)

# Bereinigen
clean:
	del /q output\*

# Phony Ziele
.PHONY: all run clean
