include build_scripts/config.mk

CC = gcc
CC16=wcc
LD16=wlink

.PHONY: all floppy_image bootloader kernel clean always

all: bootloader kernel floppy_image

#
# OS image
#
floppy_image: $(BUILD_DIR)/floppy.img

$(BUILD_DIR)/floppy.img: bootloader kernel
	@python .\build_scripts\check.py
	@python .\build_scripts\run_sh.py ./build_scripts/make_floppy_image.sh ${BUILD_DIR} $@
	@echo "--> Created: " $@

#
# Disk image
#
disk_image: $(BUILD_DIR)/main_disk.raw

$(BUILD_DIR)/main_disk.raw: bootloader kernel
	@python .\build_scripts\run_sh.py ./build_scripts/make_disk_image.sh $@ $(MAKE_DISK_SIZE) ${BUILD_DIR}
	@echo "--> Created: " $@

#
# Bootloader
#
bootloader: stage1 stage2

stage1: $(BUILD_DIR)/stage1.bin

$(BUILD_DIR)/stage1.bin: always
	@$(MAKE) -C src/bootloader/stage1 BUILD_DIR=$(abspath $(BUILD_DIR))

stage2: $(BUILD_DIR)/stage2.bin

$(BUILD_DIR)/stage2.bin: always
	@$(MAKE) -C src/bootloader/stage2 BUILD_DIR=$(abspath $(BUILD_DIR))

#
# Kernel
#
kernel: $(BUILD_DIR)/kernel.bin

$(BUILD_DIR)/kernel.bin: always
	@$(MAKE) -C src/kernel BUILD_DIR=$(abspath $(BUILD_DIR))

#
# Always
#
always:
	@$(shell mkdir $(BUILD_DIR))

#
# Clean
#
clean:
	@$(MAKE) -C src/bootloader/stage1 BUILD_DIR=$(abspath $(BUILD_DIR)) clean
	@$(MAKE) -C src/bootloader/stage2 BUILD_DIR=$(abspath $(BUILD_DIR)) clean
	@$(MAKE) -C src/kernel BUILD_DIR=$(abspath $(BUILD_DIR)) clean
	@del /q $(BUILD_DIR)\*
	@del /q $(BUILD_DIR)\stage2\asm\*
	@del /q $(BUILD_DIR)\stage2\c\*
	@del /q $(BUILD_DIR)\kernel\asm\*
	@del /q $(BUILD_DIR)\kernel\c\*