import sys

# Exit on error
def exit_on_error():
    sys.exit(1)

# Print usage
if len(sys.argv) <= 2:
    print("Usage: generate_isrs.py <isrs_gen.c> <isrs_gen.inc>")
    exit_on_error()

# Vars
ISRS_GEN_C = sys.argv[1]
ISRS_GEN_ASM = sys.argv[2]

ISRS_WITH_ERROR_CODE = set([8, 10, 11, 12, 13, 14, 17, 21, 29, 30])

#
# Generate C file
#
with open(ISRS_GEN_C, "w") as c_file:
    c_file.write("// !!! THIS FILE IS AUTOGENERATED !!!\n")
    c_file.write('#include "idt.h"\n')
    c_file.write('#include "gdt.h"\n')
    c_file.write("\n")

    for i in range(256):
        c_file.write(f"void __attribute((cdecl)) i686_ISR{i}();\n")

    c_file.write("\n")
    c_file.write("void i686_ISR_InitializeGates()\n")
    c_file.write("{\n")

    for i in range(256):
        c_file.write(f"    i686_IDT_SetGate({i}, i686_ISR{i}, i686_GDT_CODE_SEGMENT, IDT_FLAG_RING0 | IDT_FLAG_GATE_32BIT_INT);\n")

    c_file.write("}\n")

#
# Generate assembly file
#
with open(ISRS_GEN_ASM, "w") as asm_file:
    asm_file.write("; !!! THIS FILE IS AUTOGENERATED !!!\n")

    for i in range(256):
        if i in ISRS_WITH_ERROR_CODE:
            asm_file.write(f"ISR_ERRORCODE {i}\n")
        else:
            asm_file.write(f"ISR_NOERRORCODE {i}\n")
