import os

from SCons.Environment import Environment
from build_scripts.utility import GlobRecursive, FindIndex, IsFileName


Import('TARGET_ENVIRONMENT')                                                                                                                # type: ignore
TARGET_ENVIRONMENT: Environment

env = TARGET_ENVIRONMENT.Clone()
env.Append(
    LINKFLAGS = [
        '-Wl,-T', env.File('linker.ld').srcnode().path,
        '-Wl,-Map=' + env.File('terminal.map').path
    ],
    CPPPATH = [
        env.Dir('.').srcnode(),
        env['ROOTDIR'].Dir('src/libs').srcnode(),
        env['ROOTDIR'].Dir('src/userland/libs').srcnode()
    ],
    ASFLAGS = [ '-I', env.Dir('.').srcnode(), '-f', 'elf' ]
)

sources = GlobRecursive(env, '*.c') + \
          GlobRecursive(env, '*.cpp') + \
          GlobRecursive(env, '*.asm')

Import('libuser')                                                                                                                           # type: ignore

static_libs = [
    libuser                                                                                                                                 # type: ignore
]

objects = env.Object(sources)

objects = [
    *objects,
    *static_libs
]

terminal = env.Program('terminal.elf', objects)

Export('terminal')                                                                                                                          # type: ignore