import os

from SCons.Environment import Environment
from build_scripts.utility import GlobRecursive, FindIndex, IsFileName


Import('TARGET_ENVIRONMENT')                                                                                                                # type: ignore
TARGET_ENVIRONMENT: Environment

env = TARGET_ENVIRONMENT.Clone()
env.Append(
    CPPPATH = [
        env.Dir('.').srcnode(),
        env['ROOTDIR'].Dir('src/libs').srcnode(),
        env['ROOTDIR'].Dir('src/userland/libs').srcnode()
    ],
    ASFLAGS = [ '-I', env.Dir('.').srcnode(), '-f', 'elf' ]
)

sources = GlobRecursive(env, '*.c') + \
          GlobRecursive(env, '*.cpp') + \
          GlobRecursive(env, '*.asm')

objects = env.Object(sources)

libuser = env.StaticLibrary('libuser.o', objects)

Export('libuser')                                                                                                                           # type: ignore
